using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._AS.NeoNote.UI;

[GenerateTypedNameReferences]
public sealed partial class NeoNoteUiFragment : BoxContainer
{
}
